LANGUAGES = {
    "Español": {
        "title": "WinGuard",
        "subtitle": "Limpieza y seguridad para Windows",
        "tab_quick": "Limpieza rápida",
        "tab_advanced": "Modo avanzado",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Iniciar limpieza",
        "btn_defender": "Escanear con Defender",
        "btn_report": "Guardar informe",
        "btn_run": "Ejecutar selección",
        "btn_browse": "Seleccionar archivo",
        "btn_analyze": "Analizar archivo",
        "btn_clear": "Borrar registro",
        "btn_clear_all": "Desmarcar todo",
        "btn_select_all": "Seleccionar todo",
        "status_ready": "Listo para comenzar.",
        "status_running": "En ejecución...",
        "status_error": "Error: revisa los detalles.",
        "status_complete": "Completado con éxito.",
        "select_steps": "Selecciona los pasos que deseas ejecutar:",
        "quick_summary": "Limpia tu equipo en pocos clics y revisa el registro de actividad.",
        "advanced_summary": "Personaliza los pasos y ejecuta solo lo que necesites.",
        "vt_summary": "Comprueba un archivo en VirusTotal para detectar amenazas.",
        "log_header": "Registro de actividad",
        "vt_title": "Analiza un archivo con 70+ motores antivirus",
        "vt_placeholder": "Ruta del archivo...",
        "vt_no_key": "Clave API no configurada. Añade VT_API_KEY en el archivo .env",
        "vt_no_file": "Selecciona un archivo primero.",
        "vt_file_not_exists": "El archivo seleccionado no existe.",
        "report_saved": "Informe guardado en:",
        "no_steps": "Selecciona al menos un paso.",
        "defender_unavailable": "Windows Defender no está disponible en este equipo.",
    },
    "English": {
        "title": "WinGuard",
        "subtitle": "Cleanup and security for Windows",
        "tab_quick": "Quick Clean",
        "tab_advanced": "Advanced Mode",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Start cleanup",
        "btn_defender": "Scan with Defender",
        "btn_report": "Save report",
        "btn_run": "Run selection",
        "btn_browse": "Browse file",
        "btn_analyze": "Analyze file",
        "btn_clear": "Clear log",
        "btn_clear_all": "Uncheck all",
        "btn_select_all": "Select all",
        "status_ready": "Ready to begin.",
        "status_running": "Running...",
        "status_error": "Error: check the details.",
        "status_complete": "Completed successfully.",
        "select_steps": "Select the steps you want to run:",
        "quick_summary": "Clean your PC in a few clicks and review the activity log.",
        "advanced_summary": "Customize the steps and run only what you need.",
        "vt_summary": "Check a file on VirusTotal to detect threats.",
        "log_header": "Activity log",
        "vt_title": "Analyze a file with 70+ antivirus engines",
        "vt_placeholder": "File path...",
        "vt_no_key": "API key not set. Add VT_API_KEY to your .env file",
        "vt_no_file": "Please select a file first.",
        "vt_file_not_exists": "The selected file does not exist.",
        "report_saved": "Report saved at:",
        "no_steps": "Select at least one step.",
        "defender_unavailable": "Windows Defender not available on this system.",
    },
    "Deutsch": {
        "title": "WinGuard",
        "subtitle": "Bereinigung und Sicherheit für Windows",
        "tab_quick": "Schnelle Bereinigung",
        "tab_advanced": "Erweiterter Modus",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Bereinigung starten",
        "btn_defender": "Mit Defender scannen",
        "btn_report": "Bericht speichern",
        "btn_run": "Auswahl ausführen",
        "btn_browse": "Datei auswählen",
        "btn_analyze": "Datei analysieren",
        "btn_clear": "Protokoll löschen",
        "btn_clear_all": "Alle abwählen",
        "btn_select_all": "Alles auswählen",
        "status_ready": "Bereit zum Starten.",
        "status_running": "Wird ausgeführt...",
        "status_error": "Fehler: Überprüfe die Details.",
        "status_complete": "Erfolgreich abgeschlossen.",
        "select_steps": "Wähle die Schritte aus, die du ausführen möchtest:",
        "quick_summary": "Reinige deinen PC mit wenigen Klicks und überprüfe das Aktivitätsprotokoll.",
        "advanced_summary": "Passe die Schritte an und führe nur aus, was du brauchst.",
        "vt_summary": "Prüfe eine Datei mit VirusTotal auf Bedrohungen.",
        "log_header": "Aktivitätsprotokoll",
        "vt_title": "Analysiere eine Datei mit 70+ Antivirus-Engines",
        "vt_placeholder": "Dateipfad...",
        "vt_no_key": "API-Schlüssel nicht konfiguriert. Füge VT_API_KEY zur .env-Datei hinzu",
        "vt_no_file": "Bitte wähle zuerst eine Datei aus.",
        "vt_file_not_exists": "Die ausgewählte Datei existiert nicht.",
        "report_saved": "Bericht gespeichert unter:",
        "no_steps": "Bitte wähle mindestens einen Schritt aus.",
        "defender_unavailable": "Windows Defender ist auf diesem System nicht verfügbar.",
    },
}