LANGUAGES = {
    "Español": {
        "title": "WinGuard",
        "subtitle": "Limpieza y seguridad para Windows",
        "header_badge": "Rápido · Seguro · Limpio",
        "tab_quick": "Limpieza rápida",
        "tab_advanced": "Modo avanzado",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Iniciar limpieza",
        "btn_defender": "Escanear con Defender",
        "btn_report": "Guardar informe",
        "btn_run": "Ejecutar selección",
        "btn_browse": "Seleccionar archivo",
        "btn_analyze": "Analizar archivo",
        "btn_clear": "Borrar registro",
        "btn_clear_all": "Desmarcar todo",
        "btn_select_all": "Seleccionar todo",
        "status_ready": "Listo para comenzar.",
        "status_running": "En ejecución...",
        "status_error": "Error: revisa los detalles.",
        "status_complete": "Completado con éxito.",
        "select_steps": "Selecciona los pasos que deseas ejecutar:",
        "quick_summary": "Limpia tu equipo en pocos clics y revisa el registro de actividad.",
        "advanced_summary": "Personaliza los pasos y ejecuta solo lo que necesites.",
        "vt_summary": "Comprueba un archivo en VirusTotal para detectar amenazas.",
        "log_header": "Registro de actividad",
        "vt_title": "Analiza un archivo con 70+ motores antivirus",
        "vt_placeholder": "Ruta del archivo...",
        "vt_no_key": "Clave API no configurada. Añade VT_API_KEY en el archivo .env",
        "vt_no_file": "Selecciona un archivo primero.",
        "vt_file_not_exists": "El archivo seleccionado no existe.",
        "report_saved": "Informe guardado en:",
        "no_steps": "Selecciona al menos un paso.",
        "defender_unavailable": "Windows Defender no está disponible en este equipo.",
        "step_names": [
            "Temporales de usuario",
            "Temporales del sistema",
            "Prefetch",
            "Cache DNS y miniaturas",
            "Programas de inicio innecesarios",
            "Memoria virtual",
            "Papelera de reciclaje",
            "Limpieza de disco",
        ],
        "clean_user_temp": "Temporales de usuario: {count} elementos eliminados.",
        "clean_system_temp": "Temporales del sistema: {count} elementos eliminados.",
        "clean_prefetch": "Prefetch: {count} archivos eliminados.",
        "clean_dns_and_thumbnails": "Cache DNS vaciada. Miniaturas: {count} archivos eliminados.",
        "clean_startup_disabled": "Inicio deshabilitado: {items}.",
        "clean_startup_none": "Inicio: ningún programa innecesario encontrado.",
        "clean_virtual_memory": "Memoria virtual: se limpiará en cada apagado.",
        "clean_recycle_bin": "Papelera de reciclaje vaciada.",
        "clean_disk": "Limpieza de disco completada.",
        "clean_error_step": "Error en paso {index}: {error}",
        "defender_not_found": "Windows Defender no encontrado en este sistema.",
        "defender_starting": "Iniciando escaneo con Windows Defender...",
        "defender_completed": "Escaneo completado. No se encontraron amenazas.",
        "defender_threat": "AMENAZA DETECTADA. Abre Windows Defender para más detalles.",
        "defender_code": "Escaneo finalizado con código: {code}",
        "defender_error": "Error al ejecutar Windows Defender: {error}",
        "vt_api_missing": "ERROR: No se encontró la API key de VirusTotal en el archivo .env",
        "vt_file_missing": "ERROR: El archivo {filepath} no existe.",
        "vt_uploading": "Subiendo archivo a VirusTotal: {name}",
        "vt_uploaded": "Archivo subido. ID de análisis: {analysis_id}",
        "vt_waiting": "Esperando resultados (puede tardar unos segundos)...",
        "vt_result_header": "--- Resultado VirusTotal ---",
        "vt_malicious": "  Malicioso:   {count}",
        "vt_suspicious": "  Sospechoso:  {count}",
        "vt_clean": "  Limpio:      {count}",
        "vt_unknown": "  Sin datos:   {count}",
        "vt_warning_malicious": "ADVERTENCIA: El archivo es malicioso según varios motores.",
        "vt_warning_suspicious": "PRECAUCIÓN: El archivo es sospechoso según algunos motores.",
        "vt_clean_result": "El archivo parece limpio.",
        "vt_timeout": "Tiempo de espera agotado. Inténtalo de nuevo más tarde.",
        "vt_http_error": "Error HTTP: {error}",
        "vt_unexpected_error": "Error inesperado: {error}",
        "report_title": "INFORME DE LIMPIEZA - WinGuard",
        "report_date": "Fecha: {date}",
        "report_log_header": "--- LOG DE LIMPIEZA ---",
        "report_vt_header": "--- RESULTADO VIRUSTOTAL ---",
        "report_generated_by": "Generado por WinGuard - github.com/ivanvivartirado",
    },
    "English": {
        "title": "WinGuard",
        "subtitle": "Cleanup and security for Windows",
        "header_badge": "Fast · Secure · Clean",
        "tab_quick": "Quick Clean",
        "tab_advanced": "Advanced Mode",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Start cleanup",
        "btn_defender": "Scan with Defender",
        "btn_report": "Save report",
        "btn_run": "Run selection",
        "btn_browse": "Browse file",
        "btn_analyze": "Analyze file",
        "btn_clear": "Clear log",
        "btn_clear_all": "Uncheck all",
        "btn_select_all": "Select all",
        "status_ready": "Ready to begin.",
        "status_running": "Running...",
        "status_error": "Error: check the details.",
        "status_complete": "Completed successfully.",
        "select_steps": "Select the steps you want to run:",
        "quick_summary": "Clean your PC in a few clicks and review the activity log.",
        "advanced_summary": "Customize the steps and run only what you need.",
        "vt_summary": "Check a file on VirusTotal to detect threats.",
        "log_header": "Activity log",
        "vt_title": "Analyze a file with 70+ antivirus engines",
        "vt_placeholder": "File path...",
        "vt_no_key": "API key not set. Add VT_API_KEY to your .env file",
        "vt_no_file": "Please select a file first.",
        "vt_file_not_exists": "The selected file does not exist.",
        "report_saved": "Report saved at:",
        "no_steps": "Select at least one step.",
        "defender_unavailable": "Windows Defender not available on this system.",
        "step_names": [
            "User temp files",
            "System temp files",
            "Prefetch",
            "DNS cache and thumbnails",
            "Unnecessary startup programs",
            "Virtual memory",
            "Recycle bin",
            "Disk cleanup",
        ],
        "clean_user_temp": "User temp files: {count} items removed.",
        "clean_system_temp": "System temp files: {count} items removed.",
        "clean_prefetch": "Prefetch: {count} files removed.",
        "clean_dns_and_thumbnails": "DNS cache cleared. Thumbnails: {count} files removed.",
        "clean_startup_disabled": "Startup disabled: {items}.",
        "clean_startup_none": "Startup: no unnecessary programs found.",
        "clean_virtual_memory": "Virtual memory: it will be cleaned at shutdown.",
        "clean_recycle_bin": "Recycle bin emptied.",
        "clean_disk": "Disk cleanup completed.",
        "clean_error_step": "Error in step {index}: {error}",
        "defender_not_found": "Windows Defender not found on this system.",
        "defender_starting": "Starting scan with Windows Defender...",
        "defender_completed": "Scan completed. No threats were found.",
        "defender_threat": "THREAT DETECTED. Open Windows Defender for more details.",
        "defender_code": "Scan finished with code: {code}",
        "defender_error": "Error while running Windows Defender: {error}",
        "vt_api_missing": "ERROR: VirusTotal API key was not found in the .env file",
        "vt_file_missing": "ERROR: The file {filepath} does not exist.",
        "vt_uploading": "Uploading file to VirusTotal: {name}",
        "vt_uploaded": "File uploaded. Analysis ID: {analysis_id}",
        "vt_waiting": "Waiting for results (this may take a few seconds)...",
        "vt_result_header": "--- VirusTotal result ---",
        "vt_malicious": "  Malicious:   {count}",
        "vt_suspicious": "  Suspicious:  {count}",
        "vt_clean": "  Clean:       {count}",
        "vt_unknown": "  No data:     {count}",
        "vt_warning_malicious": "WARNING: The file is malicious according to several engines.",
        "vt_warning_suspicious": "CAUTION: The file is suspicious according to some engines.",
        "vt_clean_result": "The file looks clean.",
        "vt_timeout": "Timed out waiting for results. Please try again later.",
        "vt_http_error": "HTTP error: {error}",
        "vt_unexpected_error": "Unexpected error: {error}",
        "report_title": "CLEANUP REPORT - WinGuard",
        "report_date": "Date: {date}",
        "report_log_header": "--- CLEANUP LOG ---",
        "report_vt_header": "--- VIRUSTOTAL RESULT ---",
        "report_generated_by": "Generated by WinGuard - github.com/ivanvivartirado",
    },
    "Deutsch": {
        "title": "WinGuard",
        "subtitle": "Bereinigung und Sicherheit für Windows",
        "header_badge": "Schnell · Sicher · Sauber",
        "tab_quick": "Schnelle Bereinigung",
        "tab_advanced": "Erweiterter Modus",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Bereinigung starten",
        "btn_defender": "Mit Defender scannen",
        "btn_report": "Bericht speichern",
        "btn_run": "Auswahl ausführen",
        "btn_browse": "Datei auswählen",
        "btn_analyze": "Datei analysieren",
        "btn_clear": "Protokoll löschen",
        "btn_clear_all": "Alle abwählen",
        "btn_select_all": "Alles auswählen",
        "status_ready": "Bereit zum Starten.",
        "status_running": "Wird ausgeführt...",
        "status_error": "Fehler: Überprüfe die Details.",
        "status_complete": "Erfolgreich abgeschlossen.",
        "select_steps": "Wähle die Schritte aus, die du ausführen möchtest:",
        "quick_summary": "Reinige deinen PC mit wenigen Klicks und überprüfe das Aktivitätsprotokoll.",
        "advanced_summary": "Passe die Schritte an und führe nur aus, was du brauchst.",
        "vt_summary": "Prüfe eine Datei mit VirusTotal auf Bedrohungen.",
        "log_header": "Aktivitätsprotokoll",
        "vt_title": "Analysiere eine Datei mit 70+ Antivirus-Engines",
        "vt_placeholder": "Dateipfad...",
        "vt_no_key": "API-Schlüssel nicht konfiguriert. Füge VT_API_KEY zur .env-Datei hinzu",
        "vt_no_file": "Bitte wähle zuerst eine Datei aus.",
        "vt_file_not_exists": "Die ausgewählte Datei existiert nicht.",
        "report_saved": "Bericht gespeichert unter:",
        "no_steps": "Bitte wähle mindestens einen Schritt aus.",
        "defender_unavailable": "Windows Defender ist auf diesem System nicht verfügbar.",
        "step_names": [
            "Benutzertempodateien",
            "System-Tempodateien",
            "Prefetch",
            "DNS-Cache und Miniaturansichten",
            "Unnötige Startprogramme",
            "Virtueller Speicher",
            "Papierkorb",
            "Festplattenbereinigung",
        ],
        "clean_user_temp": "Benutzertempodateien: {count} Elemente entfernt.",
        "clean_system_temp": "System-Tempodateien: {count} Elemente entfernt.",
        "clean_prefetch": "Prefetch: {count} Dateien entfernt.",
        "clean_dns_and_thumbnails": "DNS-Cache geleert. Miniaturansichten: {count} Dateien entfernt.",
        "clean_startup_disabled": "Start deaktiviert: {items}.",
        "clean_startup_none": "Start: keine unnötigen Programme gefunden.",
        "clean_virtual_memory": "Virtueller Speicher: wird beim Herunterfahren bereinigt.",
        "clean_recycle_bin": "Papierkorb geleert.",
        "clean_disk": "Festplattenbereinigung abgeschlossen.",
        "clean_error_step": "Fehler in Schritt {index}: {error}",
        "defender_not_found": "Windows Defender wurde auf diesem System nicht gefunden.",
        "defender_starting": "Scan mit Windows Defender wird gestartet...",
        "defender_completed": "Scan abgeschlossen. Es wurden keine Bedrohungen gefunden.",
        "defender_threat": "BEDROHUNG ERKANNT. Öffne Windows Defender für weitere Details.",
        "defender_code": "Scan beendet mit Code: {code}",
        "defender_error": "Fehler beim Ausführen von Windows Defender: {error}",
        "vt_api_missing": "FEHLER: Der VirusTotal-API-Schlüssel wurde in der .env-Datei nicht gefunden",
        "vt_file_missing": "FEHLER: Die Datei {filepath} existiert nicht.",
        "vt_uploading": "Datei wird zu VirusTotal hochgeladen: {name}",
        "vt_uploaded": "Datei hochgeladen. Analyse-ID: {analysis_id}",
        "vt_waiting": "Warte auf Ergebnisse (das kann einige Sekunden dauern)...",
        "vt_result_header": "--- VirusTotal-Ergebnis ---",
        "vt_malicious": "  Schädlich:   {count}",
        "vt_suspicious": "  Verdächtig:  {count}",
        "vt_clean": "  Sauber:      {count}",
        "vt_unknown": "  Keine Daten: {count}",
        "vt_warning_malicious": "WARNUNG: Die Datei ist laut mehreren Engines bösartig.",
        "vt_warning_suspicious": "VORSICHT: Die Datei wird von einigen Engines als verdächtig eingestuft.",
        "vt_clean_result": "Die Datei scheint sauber zu sein.",
        "vt_timeout": "Zeitüberschreitung beim Warten auf Ergebnisse. Bitte später erneut versuchen.",
        "vt_http_error": "HTTP-Fehler: {error}",
        "vt_unexpected_error": "Unerwarteter Fehler: {error}",
        "report_title": "BEREINIGUNGSBERICHT - WinGuard",
        "report_date": "Datum: {date}",
        "report_log_header": "--- BEREINIGUNGS-LOG ---",
        "report_vt_header": "--- VIRUSTOTAL-ERGEBNIS ---",
        "report_generated_by": "Erstellt mit WinGuard - github.com/ivanvivartirado",
    },
}


def translate_message(lang, key, **kwargs):
    if not lang:
        template = key
    else:
        template = lang.get(key, key)
    if kwargs:
        try:
            return template.format(**kwargs)
        except Exception:
            return template
    return template