LANGUAGES = {
    "Español": {
        "title": "WinGuard",
        "subtitle": "Limpieza y seguridad para Windows",
        "tab_quick": "Limpieza rápida",
        "tab_advanced": "Modo avanzado",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Iniciar limpieza completa",
        "btn_defender": "Escanear con Defender",
        "btn_report": "Guardar informe",
        "btn_run": "Ejecutar selección",
        "btn_browse": "Seleccionar archivo",
        "btn_analyze": "Analizar archivo",
        "status_ready": "Listo para limpiar.",
        "select_steps": "Selecciona los pasos que quieres ejecutar:",
        "vt_title": "Analiza un archivo con 70+ motores antivirus",
        "vt_placeholder": "Ruta del archivo...",
        "vt_no_key": "API key no configurada. Añade VT_API_KEY en el archivo .env",
        "vt_no_file": "Selecciona un archivo primero.",
        "report_saved": "Informe guardado en:",
        "no_steps": "Selecciona al menos un paso.",
        "defender_unavailable": "Windows Defender no disponible en este sistema.",
    },
    "English": {
        "title": "WinGuard",
        "subtitle": "Cleanup and security for Windows",
        "tab_quick": "Quick Clean",
        "tab_advanced": "Advanced Mode",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Start full cleanup",
        "btn_defender": "Scan with Defender",
        "btn_report": "Save report",
        "btn_run": "Run selection",
        "btn_browse": "Browse file",
        "btn_analyze": "Analyze file",
        "status_ready": "Ready to clean.",
        "select_steps": "Select the steps you want to run:",
        "vt_title": "Analyze a file with 70+ antivirus engines",
        "vt_placeholder": "File path...",
        "vt_no_key": "API key not set. Add VT_API_KEY to your .env file",
        "vt_no_file": "Please select a file first.",
        "report_saved": "Report saved at:",
        "no_steps": "Select at least one step.",
        "defender_unavailable": "Windows Defender not available on this system.",
    },
    "Deutsch": {
        "title": "WinGuard",
        "subtitle": "Bereinigung und Sicherheit für Windows",
        "tab_quick": "Schnelle Bereinigung",
        "tab_advanced": "Erweiterter Modus",
        "tab_vt": "VirusTotal",
        "btn_quick_clean": "Komplette Bereinigung starten",
        "btn_defender": "Mit Defender scannen",
        "btn_report": "Bericht speichern",
        "btn_run": "Auswahl ausführen",
        "btn_browse": "Datei auswählen",
        "btn_analyze": "Datei analysieren",
        "status_ready": "Bereit zur Bereinigung.",
        "select_steps": "Wähle die auszuführenden Schritte:",
        "vt_title": "Analysiere eine Datei mit 70+ Antivirus-Engines",
        "vt_placeholder": "Dateipfad...",
        "vt_no_key": "API-Schlüssel nicht konfiguriert. Füge VT_API_KEY zur .env-Datei hinzu",
        "vt_no_file": "Bitte zuerst eine Datei auswählen.",
        "report_saved": "Bericht gespeichert unter:",
        "no_steps": "Bitte mindestens einen Schritt auswählen.",
        "defender_unavailable": "Windows Defender ist auf diesem System nicht verfügbar.",
    },
}